// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvkBU65x76henG3m8AOrPlT6RCzS2qSt8',
    appId: '1:732530504308:web:fa39ae88bd505428f11721',
    messagingSenderId: '732530504308',
    projectId: 'mainproject-c4112',
    authDomain: 'mainproject-c4112.firebaseapp.com',
    databaseURL: 'https://mainproject-c4112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mainproject-c4112.firebasestorage.app',
    measurementId: 'G-762XL8B29H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBviH-yWm0zktCwJifH3Q2Ppb1LutrCLL8',
    appId: '1:732530504308:android:e1f768abd65de474f11721',
    messagingSenderId: '732530504308',
    projectId: 'mainproject-c4112',
    databaseURL: 'https://mainproject-c4112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mainproject-c4112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf9HC-ECWc1aRu0IsdkM8oIqeBjlnr-Ns',
    appId: '1:732530504308:ios:d4481579ae99908af11721',
    messagingSenderId: '732530504308',
    projectId: 'mainproject-c4112',
    databaseURL: 'https://mainproject-c4112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mainproject-c4112.firebasestorage.app',
    iosBundleId: 'com.example.linkride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf9HC-ECWc1aRu0IsdkM8oIqeBjlnr-Ns',
    appId: '1:732530504308:ios:d4481579ae99908af11721',
    messagingSenderId: '732530504308',
    projectId: 'mainproject-c4112',
    databaseURL: 'https://mainproject-c4112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mainproject-c4112.firebasestorage.app',
    iosBundleId: 'com.example.linkride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvkBU65x76henG3m8AOrPlT6RCzS2qSt8',
    appId: '1:732530504308:web:f4dbbff41ff51453f11721',
    messagingSenderId: '732530504308',
    projectId: 'mainproject-c4112',
    authDomain: 'mainproject-c4112.firebaseapp.com',
    databaseURL: 'https://mainproject-c4112-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mainproject-c4112.firebasestorage.app',
    measurementId: 'G-TDR8MD97QN',
  );

}